services:
  - type: web
    name: line-schedule-bot
    env: python
    plan: free
    region: singapore      # 低延遲區，可任意
    branch: main           # 你的 Git branch
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    healthCheckPath: /
    envVars:
      - key: LINE_CHANNEL_ACCESS_TOKEN
        sync: false        # 部署後手動填入
      - key: LINE_CHANNEL_SECRET
        sync: false        # 部署後手動填入
      - key: TARGET_ID
        sync: false        # 部署後手動填入
